backend/routes.py
import json
import requests

from flask import (
    render_template,
    make_response,
    jsonify,
    abort,
    request,
    url_for,
    session,
    redirect,
    flash,
    Blueprint,
    current_app,
)

from backend import db
from backend.models import Customer, Order
from backend.forms import UpdateCustomerForm, MakeOrderForm

bp = Blueprint("main", __name__)


@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
def index():
    sesison_info = session.get("user")
    if sesison_info:  # logged in users.
        name = sesison_info["userinfo"]["name"]
        email = sesison_info["userinfo"]["email"]
        contact = "NULL"  # default if we cannot extract the contact from Google
        if "phoneNumbers" in sesison_info["personData"]:
            # attempt to extract contact from Google
            contact = sesison_info["personData"]["phoneNumbers"][0]["canonicalForm"]
            contact = contact.split("+")[-1]

        # database logic
        customer = Customer.query.filter_by(email=email).first()
        if not customer:
            customer = Customer(name=name, email=email, contact=contact)
            db.session.add(customer)
            db.session.commit()

        # update customer
        form = UpdateCustomerForm()
        if form.validate_on_submit():
            # Extract form data
            name = form.name.data
            email = form.email.data
            contact = form.contact.data

            # send PUT request to our API to update the data
            data = {"name": name, "email": email, "contact": contact}
            headers = {"Content-Type": "application/json"}
            response = requests.put(
                f'{url_for("main.update_customer", customer_id=customer.id, _external=True)}',
                data=json.dumps(data),
                headers=headers,
            )
            if response.status_code == 201:
                flash("Records updated successfully")
            else:
                flash("Failed to update customer", category="danger")

            return redirect(url_for("main.index"))

        return render_template(
            "index.html",
            title="Home",
            session=sesison_info,
            customer=customer,
            form=form,
        )
    return render_template("index.html", title="Home", session=sesison_info)


# login + logout endpoints
@bp.route("/login")
def login():
    return current_app.orders_api_auth.authorize_redirect(
        redirect_uri=url_for("main.google_callback", _external=True)
    )


@bp.route("/google-login")
def google_callback():
    token = current_app.orders_api_auth.authorize_access_token()
    personDataUrl = (
        "https://people.googleapis.com/v1/people/me?personFields=phoneNumbers"
    )
    personData = requests.get(
        personDataUrl, headers={"Authorization": f"Bearer {token['access_token']}"}
    ).json()

    token["personData"] = personData  # contacts from Google are located in personData
    session["user"] = token

    return redirect(url_for("main.index"))


@bp.route("/logout")
def logout():
    session.pop("user")
    return redirect(url_for("main.index"))


@bp.route("/orders", methods=["GET", "POST"])
def orders():
    sesison_info = session.get("user")
    if sesison_info:
        email = sesison_info["userinfo"]["email"]
        customer = Customer.query.filter_by(email=email).first()
        orders = Order.query.filter_by(customer_id=customer.id).all()

        form = MakeOrderForm()
        if form.validate_on_submit():
            # Extract form data
            item = form.item.data
            amount = round(float(form.amount.data), 2)

            # send PUT request to our API to update the data
            data = {"customer_id": customer.id, "item": item, "amount": amount}
            headers = {"Content-Type": "application/json"}
            response = requests.post(
                f'{url_for("main.create_order", _external=True)}',
                data=json.dumps(data),
                headers=headers,
            )
            if response.status_code == 201:
                flash("Order made successfully")
                # try and send the order confirmation SMS
                try:
                    message = f"Thank you {customer.name} for making an order of {item} for amount Ksh.{amount}"
                    contact = f"+{customer.contact}"
                    sender = current_app.config.get("AFRICASTALKING_SENDER_ID")
                    response = current_app.sms_service.send(message, [contact], sender)
                    print(f"[MESSAGE RESPONSE]: {response}")
                except Exception as e:
                    print(f"[MESSAGE ERROR]: {e}")

            else:
                flash("Failed to make order", category="danger")

            return redirect(url_for("main.orders"))

        return render_template(
            "orders.html",
            title="Orders",
            session=sesison_info,
            orders=orders,
            form=form,
        )

    return render_template("orders.html", title="Orders", session=sesison_info)


# API Endpoints
# Customer Endpoints
@bp.route("/api/v1/customers", methods=["GET"])
def get_customers():
    """Get all customers present in the database
    Specifications
    ---
    responses:
      201:
        description: Data for all the customers
    """
    customers = Customer.query.all()
    customer_list = [
        {"id": c.id, "name": c.name, "email": c.email, "contact": c.contact}
        for c in customers
    ]
    return jsonify(customer_list), 201


@bp.route("/api/v1/customers/<int:customer_id>", methods=["GET"])
def get_customer(customer_id):
    """Get a specific customer from database
    Specifications
    ---
    parameters:
      - name: customer_id
        in: customer id
        type: int
        required: true
    responses:
      200:
        description: Data for the customer requested
      404:
        description: Customer does not exist in the database
    """
    customer = Customer.query.get(customer_id)
    if customer:
        return (
            jsonify(
                {
                    "id": customer.id,
                    "name": customer.name,
                    "email": customer.email,
                    "contact": customer.contact,
                }
            ),
            200,
        )
    abort(404)


@bp.route("/api/v1/customers", methods=["POST"])
def create_customer():
    """Create a customer in the database
    Specifications
    ---
    parameters:
      - name: data
        description: data for the customer
        in: data
        type: json
        required: true
    responses:
      200:
        description: Data for the customer created
      400:
        description: Missing some fields in the data you provided
    """
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided!"}), 400
    required_fields = ["name", "email", "contact"]
    for field in required_fields:
        if field not in data:
            return (
                jsonify({"error": f"Missing {field} field in the data provided!"}),
                400,
            )
    customer = {f"{field}": data.get(f"{field}") for field in required_fields}
    new_customer = Customer(
        name=customer["name"], email=customer["email"], contact=customer["contact"]
    )
    db.session.add(new_customer)
    db.session.commit()

    return (
        jsonify(
            {
                "id": new_customer.id,
                "name": new_customer.name,
                "email": new_customer.email,
                "contact": new_customer.contact,
            }
        ),
        201,
    )


@bp.route("/api/v1/customers/<int:customer_id>", methods=["PUT"])
def update_customer(customer_id):
    """Update a customer in the database
    Specifications
    ---
    parameters:
      - name: customer_id
        description: id for the customer to update
        in: customer_id
        type: int
        required: true
      - name: data
        description: data for the customer
        in: data
        type: json
        required: true
    responses:
      200:
        description: Data for the customer updated
      400:
        description:  Missing some fields in the data you provided
    """
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided!"}), 400
    required_fields = ["name", "email", "contact"]
    for field in required_fields:
        if field not in data:
            return (
                jsonify({"error": f"Missing {field} field in the data provided!"}),
                400,
            )
    customer = Customer.query.get(customer_id)
    if customer:
        customer.name = data["name"]
        customer.email = data["email"]
        customer.contact = data["contact"]
        db.session.commit()
        return (
            jsonify(
                {
                    "id": customer.id,
                    "name": customer.name,
                    "email": customer.email,
                    "contact": customer.contact,
                }
            ),
            201,
        )
    return jsonify({"message": "Customer not found"}), 404


@bp.route("/api/v1/customers/<int:customer_id>", methods=["DELETE"])
def delete_customer(customer_id):
    """Delete a customer in the database
    Specifications
    ---
    parameters:
      - name: customer_id
        description: id for the customer to delete
        in: data
        type: int
        required: true
    responses:
      201:
        description: Customer deleted
      400:
        description: Customer not found
    """
    customer = Customer.query.get(customer_id)
    if customer:
        db.session.delete(customer)
        db.session.commit()
        return jsonify({"message": "Customer deleted"}), 201
    return jsonify({"message": "Customer not found"}), 404


# Order Endpoints

backend/templates/base.html
<!doctype html>
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - Orders API</title>
    {% else %}
    <title>Welcome to Orders API</title>
    {% endif %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
        <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Orders API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only"></span></a>
                {% if session %}
                <a class="nav-item nav-link" href="{{url_for('main.orders')}}">Orders</a>
                <a class="nav-item nav-link" href="{{url_for('main.logout')}}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{url_for('main.login')}}">Log In with Google</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% if category == 'message' %}
        <div class="alert alert-dismissible fade show alert-info container" role="alert">
            {% else %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {% endif %}
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        {% block scripts %}{% endblock %}

</body>

</html>

backend/templates/index.html
{% extends "base.html" %}

{% block content %}
{% if session %}
<div>
    <h4>Profile</h4>
    {% if customer.contact == 'NULL' %}
    <p>Kindly update your <b>Contact</b> details in order to make orders.</p>
    {% else %}
    <p>You can make <a href="{{url_for('main.orders')}}">orders</a></p>
    {% endif %}
    <table id="customer" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ customer.name }}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.contact }}</td>
            </tr>
        </tbody>
    </table>
    <h4>Update Profile</h4>
    <p>Fill in all details when updating your profile.</p>
    <form method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
        </p>
        <p>
            {{ form.contact.label }}<br>
            {{ form.contact(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% else %}
<div>
    <p>Hello, Stranger! Kindly log with Google to continue.</p>
</div>
{% endif %}
{% endblock %}

backend/templates/orders.html
{% extends "base.html" %}

{% block content %}
{% if session %}
<div>
    <h4>Orders</h4>
    <p>Your past orders</p>
    <table id="orders" class="table table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>Amount (Ksh)</th>
                <th>Time (YYYY-MM-DD H:M)</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.item }}</td>
                <td>{{ order.amount }}</td>
                <td>{{ order.time.strftime('%Y-%m-%d %H:%m') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h4>Make an Order</h4>
    <p>In order to receive the confirmation message after making an order, make sure you have done the following:</p>
    <ul>
        <li>Updated your contant details in your profile: <a href="{{url_for('main.index')}}">Profile</a></li>
        <li>Launched a simulator on Africas Talking Sandbox with the number on your profile <a
                href="https://developers.africastalking.com/simulator">Africas Talking Sandbox</a></li>
    </ul>
    <form method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.item.label }}<br>
            {{ form.item(size=32) }}
        </p>
        <p>
            {{ form.amount.label }}<br>
            {{ form.amount(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% else %}
<div>
    <p>Hello, Stranger! You cannot make orders until you log in</p>
</div>
{% endif %}
{% endblock %}